import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Research Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-3xl mx-auto flex flex-col items-center justify-start mt-12 sm:mt-16 space-y-8 sm:space-y-10 px-4 sm:px-6 lg:px-8`}
      >
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground tracking-tighter text-center">
          AI Research Agent
        </h1>
        <main className="w-full max-w-3xl">{children}</main>
      </body>
    </html>
  );
}
